#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd infrastructure || exit 1

echo "Running terraform fmt check..."
terraform fmt -check -recursive

echo "Running terraform validate..."
terraform init -backend=false
terraform validate

echo "Running tflint..."
tflint --init
tflint
